mport csv import time from datetime import date, datetime from pathlib import Path import altair as alt import pandas as pd import streamlit as st SAMPLE_DATA_FILE = Path(__file__).parent / "sample_data.psv" def load_sample_transactions(): """Load the bundled sample_data.psv file into the app's transaction format.""" if not SAMPLE_DATA_FILE.exists(): st.error(f"ไม่พบไฟล์ข้อมูลตัวอย่าง: {SAMPLE_DATA_FILE.name}") return [] transactions = [] with SAMPLE_DATA_FILE.open( "r", encoding="utf-8-sig", newline="", ) as sample_file: reader = csv.DictReader(sample_file, delimiter="|") for row in reader: transactions.append( { "วันที่": datetime.strptime( row["วันที่"], "%Y-%m-%d", ).date(), "ประเภท": row["ประเภท"], "หมวดหมู่": row["หมวดหมู่"], "จำนวนเงิน (บาท)": float(row["จำนวนเงิน"]), "รายละเอียด": row["รายละเอียด"].strip() or "-", } ) return transactions st.set_page_config( page_title="FinSight AI", page_icon="💸", layout="wide", initial_sidebar_state="collapsed", ) st.markdown( """ """, unsafe_allow_html=True, ) st.markdown( """
Personal finance workspace
FinSight AI
บันทึกทุกความเคลื่อนไหวทางการเงินให้เป็นระเบียบในที่เดียว

""", unsafe_allow_html=True, ) if "transactions" not in st.session_state: st.session_state.transactions = load_sample_transactions() categories = [ "เงินเดือน", "รายได้เสริม", "อาหาร", "เดินทาง", "ช้อปปิง", "ค่าสาธารณูปโภค", "ที่พักอาศัย", "หนี้สิน", "อื่นๆ", ] left_column, right_column = st.columns( [0.9, 1.45], gap="large", ) with left_column: st.markdown( '
เพิ่มรายการใหม่
', unsafe_allow_html=True, ) st.markdown( '
' "กรอกรายละเอียดรายรับหรือรายจ่ายของคุณ" "
", unsafe_allow_html=True, ) with st.form( "transaction_form", clear_on_submit=True, ): transaction_date = st.date_input( "วันที่", value=date.today(), ) transaction_type = st.selectbox( "ประเภท", ["รายรับ", "รายจ่าย"], ) category = st.selectbox( "หมวดหมู่", categories, ) amount = st.number_input( "จำนวนเงิน", min_value=0.0, value=0.0, step=100.0, format="%.2f", ) details = st.text_input( "รายละเอียด", placeholder="เช่น ค่าอาหารกลางวัน", ) submitted = st.form_submit_button( "บันทึกข้อมูล", width="stretch", ) if submitted: if amount <= 0: st.warning("กรุณาระบุจำนวนเงินที่มากกว่า 0 บาท") else: st.session_state.transactions.append( { "วันที่": transaction_date, "ประเภท": transaction_type, "หมวดหมู่": category, "จำนวนเงิน (บาท)": amount, "รายละเอียด": details.strip() or "-", } ) st.success("บันทึกข้อมูลเรียบร้อยแล้ว") with right_column: transaction_count = len(st.session_state.transactions) total_income = sum( item["จำนวนเงิน (บาท)"] for item in st.session_state.transactions if item["ประเภท"] == "รายรับ" ) total_expense = sum( item["จำนวนเงิน (บาท)"] for item in st.session_state.transactions if item["ประเภท"] == "รายจ่าย" ) balance = total_income - total_expense st.markdown( f"""
รายการทั้งหมด
{transaction_count}
คงเหลือ
{balance:,.2f} บาท

""", unsafe_allow_html=True, ) st.markdown( '
' "รายการทางการเงิน" "
", unsafe_allow_html=True, ) if st.session_state.transactions: st.dataframe( st.session_state.transactions, width="stretch", hide_index=True, column_config={ "วันที่": st.column_config.DateColumn( "วันที่", format="DD/MM/YYYY", ), "จำนวนเงิน (บาท)": st.column_config.NumberColumn( "จำนวนเงิน (บาท)", format="฿%.2f", ), }, ) expense_rows = [ transaction for transaction in st.session_state.transactions if transaction["ประเภท"] == "รายจ่าย" ] if expense_rows: expenses_by_category = {} for transaction in expense_rows: category_name = transaction["หมวดหมู่"] expenses_by_category[category_name] = ( expenses_by_category.get(category_name, 0) + transaction["จำนวนเงิน (บาท)"] ) chart_data = pd.DataFrame( [ { "category": category_name, "amount": total_amount, } for category_name, total_amount in expenses_by_category.items() ] ) st.markdown( '
' "สัดส่วนรายจ่ายตามหมวดหมู่" "
", unsafe_allow_html=True, ) pie_chart = ( alt.Chart(chart_data) .mark_arc( innerRadius=58, outerRadius=120, ) .encode( theta=alt.Theta( "amount:Q", aggregate="sum", title="จำนวนเงิน", scale=alt.Scale( domain=[ 0, float(chart_data["amount"].sum()), ] ), ), color=alt.Color( "category:N", title="หมวดหมู่", legend=alt.Legend(orient="right"), ), tooltip=[ alt.Tooltip( "category:N", title="หมวดหมู่", ), alt.Tooltip( "amount:Q", title="รายจ่าย", format=",.2f", ), ], ) .properties(height=300) ) st.altair_chart( pie_chart, use_container_width=True, ) # --- ส่วนที่ 3: ระบบ AI Advisor และ พยากรณ์แนวโน้ม --- st.markdown('
🤖 AI Financial Advisor & พยากรณ์แนวโน้ม
', unsafe_allow_html=True) if st.button("✨ วิเคราะห์พฤติกรรมการเงินด้วย AI", type="primary", use_container_width=True): with st.spinner("AI กำลังวิเคราะห์ข้อมูลของคุณ..."): time.sleep(1.5) # จำลองเวลาที่ AI คิดประมวลผล # 1. หาหมวดหมู่ที่จ่ายเยอะสุด highest_cat = max(expenses_by_category, key=expenses_by_category.get) highest_amt = expenses_by_category[highest_cat] # 2. คำนวณอัตราการออมและเงินสำรอง savings_rate = (balance / total_income * 100) if total_income > 0 else 0 emergency_fund = total_expense * 6 # 3. พยากรณ์ค่าใช้จ่ายล่วงหน้า unique_days = len(set(t["วันที่"] for t in expense_rows)) forecast_30_days = (total_expense / unique_days * 30) if unique_days > 0 else 0 st.success("✅ วิเคราะห์เสร็จสิ้น! นี่คือคำแนะนำสำหรับคุณ:") st.info(f"💡 **วิเคราะห์รายจ่าย:** พบว่าหมวด **'{highest_cat}'** มีค่าใช้จ่ายสูงสุด ({highest_amt:,.2f} บาท) แนะนำให้ทบทวนงบส่วนนี้") if savings_rate >= 20: st.info(f"💰 **เป้าหมายการออม:** ยอดเยี่ยม! อัตราการออมของคุณคือ **{savings_rate:.1f}%** (ผ่านเกณฑ์ ≥ 20%)") elif savings_rate > 0: st.warning(f"💰 **เป้าหมายการออม:** ปัจจุบันออมได้ **{savings_rate:.1f}%** แนะนำให้ลดรายจ่ายเพื่อเพิ่มเงินออมให้ถึง 20%") else: st.error(f"💰 **เป้าหมายการออม:** คุณไม่มีเงินออมในระบบ AI แนะนำให้ลดรายจ่ายหมวด '{highest_cat}' ด่วน") st.info(f"🛡️ **ความมั่นคง:** แนะนำให้สร้างกองทุนฉุกเฉินครอบคลุม 6 เดือน (เป้าหมาย: **{emergency_fund:,.2f} บาท**)") if forecast_30_days > 0: st.info(f"📈 **พยากรณ์ล่วงหน้า:** จากพฤติกรรม {unique_days} วันที่ผ่านมา คาดการณ์ว่ารายจ่าย 30 วันข้างหน้าจะอยู่ที่ **{forecast_30_days:,.2f} บาท**") if forecast_30_days > total_income and total_income > 0: st.error("⚠️ คำเตือน: แนวโน้มค่าใช้จ่ายเดือนหน้าสูงกว่ารายรับ! แนะนำให้รัดเข็มขัดทันที") # ---------------------------------------- else: st.info("ยังไม่มีรายการ เริ่มต้นด้วยการบันทึกข้อมูลจากแบบฟอร์มด้านซ้าย")
